apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: scaleway
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: id:{{ .Values.scaleway.secretId }}
        version: latest_enabled
        property: secret_key
    - secretKey: postgres_password
      remoteRef:
        key: id:{{ .Values.scaleway.secretId }}
        version: latest_enabled
        property: postgres_password
    - secretKey: inclusion_connect_client_id
      remoteRef:
        key: id:{{ .Values.scaleway.secretId }}
        version: latest_enabled
        property: inclusion_connect_client_id
    - secretKey: inclusion_connect_client_secret
      remoteRef:
        key: id:{{ .Values.scaleway.secretId }}
        version: latest_enabled
        property: inclusion_connect_client_secret
    - secretKey: bootstrap_admin_password
      remoteRef:
        key: id:{{ .Values.scaleway.secretId }}
        version: latest_enabled
        property: bootstrap_admin_password
    - secretKey: bootstrap_admin_email
      remoteRef:
        key: id:{{ .Values.scaleway.secretId }}
        version: latest_enabled
        property: bootstrap_admin_email
