apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.interops-a.inclusion.gouv.fr`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
  tls:
    certResolver: letsencrypt
