{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-config
  namespace: {{ include "interops.namespace" . }}
  labels:
    {{- include "interops.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: vpn-config
    creationPolicy: Owner
  data:
    - secretKey: local_ip
      remoteRef:
        key: id:{{ .Values.externalSecrets.remoteSecretId }}
        version: latest_enabled
        property: local_ip_{{ .Values.environment }}
    - secretKey: remote_ip
      remoteRef:
        key: id:{{ .Values.externalSecrets.remoteSecretId }}
        version: latest_enabled
        property: remote_ip_{{ .Values.environment }}
{{- end }}
