# Values for production environment

ingress:
  hosts:
    - host: admin.production.interops-a.inclusion.gouv.fr
      paths:
        - path: /
          pathType: Prefix

env:
  - name: ENVIRONMENT
    value: "production"
