api:
    allowedSourceRanges:
        - ENC[AES256_GCM,data:iMtdvuqbEC1zYhQjH+sxVOG0Zhq1mG6RHqJ6,iv:y6osl3BZafRU89ECrfW/vMyA2n/zjNpZ6pegzS09qLw=,tag:6ymttaUgIoyjqpCDyZykIw==,type:comment]
        - ENC[AES256_GCM,data:Jhxowfv6zUewYRsqAlAa,iv:d81eOSPjgUdTEz9zNjl8i1PZjr7CL0TmSD/pRx1MO50=,tag:A8WiNCnKra1K0p55VA6VXA==,type:str]
        - ENC[AES256_GCM,data:FaSV8+/89NImScusONHAhkZ3Tfv50h+TggRG,iv:E3Zgi8lfKn2sboNBTU7eLs8zfv8UX0SLZMBl/tqWKjk=,tag:/R8KDKEMRwi39JSr6h1+7g==,type:comment]
        - ENC[AES256_GCM,data:TNT20MICT/b6Aime+mQ4gg==,iv:gMC1mPryFBj9Y4VSMPe2PsUVz2dYQ30AhoVz1/svmTI=,tag:EtPYIP6culRmNVQJr7r8BA==,type:str]
        - ENC[AES256_GCM,data:2vo/hnB6/wWCWGyQJYr/q0k=,iv:rHWDv4FE5hXik0O5/wYSLONfqJyjQrL61KUG2svDYBM=,tag:87qZ+iymT1JfGTdTd+a6pQ==,type:comment]
        - ENC[AES256_GCM,data:NNO2nLnWgqtRtRaDDQ==,iv:RG/GR2a9IQ8CaEuPl5G8eDnkySF/zgzKaS73ltHYLrw=,tag:DrYOg9RZNvPUa8yQYtM1xw==,type:str]
        - ENC[AES256_GCM,data:6nqzPPiMvTm4SP8kaKDs5DKFwg==,iv:mxMBZWZJDUilcSmhpzA3eM9EW9PgHgOu7hGXinq8YXM=,tag:JOmI3SVo278TXJFf6wqLbg==,type:comment]
        - ENC[AES256_GCM,data:z5HSh7PktReef046uwA=,iv:K04YEIm9qizPGV30PhZP1BE/fQb9K78FpsXEMtNIOAc=,tag:lA47xmVVJj+GJ6ylNgy6fg==,type:str]
        - ENC[AES256_GCM,data:kyCGITmTlOacJ3QAqCa3OJQAlYg=,iv:/OH7BAWti5h4a+8vgkzTwtCa+WjYHfE3UD21r/hKLHE=,tag:GRndiSaLVqF28qkLgEXveQ==,type:comment]
        - ENC[AES256_GCM,data:/zSU0tFL3EEC92u3zydf,iv:eh6hVtAHUV8TcZjw0OzDCUPdkrwdOx1XHah02fMOzUA=,tag:6H1Hqcwh45DteTQTwX/DUw==,type:str]
interops:
    organizationCode: ENC[AES256_GCM,data:JZd3eg==,iv:wRDsSiSWEUfT4rQ8xj4rHmBnx2SS690plX9/gVZcJN8=,tag:4s4tcWQ29mAW+fu9n6ApeQ==,type:int]
    organizationLabel: ENC[AES256_GCM,data:xF9wNPfSaI5xiZ+LtQ==,iv:vPE2xlZKjrRcr2cgmhs/w99jW7fDKBG3yJlaEB5MXRM=,tag:4+Fl9Sk00HugKJt3/1pZsg==,type:str]
    subjectId: ENC[AES256_GCM,data:VL3bBJEE/dvliDwKZaPhPsB7IiWRd4UnaXwfkrAlGjI29Za9LiDQ,iv:k8LyKAj2XBH3iic52AKZElZhOdqB98qKNzKM3bcgu34=,tag:xcPC9n4wVCGi7THLtALB8w==,type:str]
    identityPath: ENC[AES256_GCM,data:ZsR0hxU9hjWT3ai6DRFBF7WBY0+2nGNeYOsFm3JIVgk=,iv:L4m2IsMpEmqArFVh9pNUh3zQ2xjZIf8Aej/Dr5/OOl4=,tag:TNNgfz6lkLHeTRp+VQG6NQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgTWVhT3N3IEJQMnl3WWhG
            NC93cGt1cERVbEJsSFRBT0Z6NTRXc3dVMjdrb1poNmdXMDI3L3gzOWFLMGdnQ2t3
            allxd0VqVnpjc1ZQanRBOU85dFFFU2JKM3c0cmJzWQpPK0hWY3crdmsvY25vdDJZ
            R3h6czNqR0NnOVlWNEI2OGRzeCtlUkNpRkZNCi0tLSA2OTFkS05tYkVUUGlVVXhk
            Y0xybkNWYTF2N1BYMzY2bkhSRzB6TzUyQVh3CuMdpQ55EIfLw5AAIjLff8e3Mgly
            VsWnJUdfEV/uTSH5DOdMK/Zc4MX2OsfSLEmBh9Zm7FeLw9vOKAy/QiAirOs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSlRTc1V4Q0VLaFNNZm5h
            ODBtUjh0SVBHWnRpTWZaUUwwZXU2Tlh1RVE4Clp3dHZDRTFGOVZ4YmNMT2hwMFhI
            anRlZDZONy8xV05jd1RxMVFGOHVDVHMKLS0tIFlqMitJQm9lQm5DTWpMMzBpbDR3
            VDFkd3RtcC9nTWM5Z1pOT040NzhJVGsK5a0TCXbNsQ59NdNSt4lX9769Ab6nSJmC
            XayGDQzvCnh0FdN2nbI8ZCzhFrHzpWTlvICOJgJ6PAg4M+I0GdRmYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgMVZFbitRIEJNWjBQTjVO
            TkU1dTRFZ2pLN2hINEd6OHh5cmRVZGZQM3psQTZSallEdWJMZUlzUjBvZlNmR21j
            US9ta3RZN0w5ZGh2S3ljYm82NUNWYkdmQkR2VUxocwpDMjNkdGkzZEZmUlBuNTFF
            Y1lRd1JGYzdENkw3MG0rZ1BqMEZmZEpTUkVNCi0tLSAxY2pka1hCQ1JGbHJhQ1Fq
            TVUrL2ZLZmdCRGFrVWpKSDlId0hJVXljTmVVCm1xrClOy02lE1hkmuu4QFiVAaby
            Z4LQoD7kau6+KUbWDh98FUjyMxLvUNj4AGff1WROe8UT8FVhOmTPt2MkHP4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tpm1qdeuratg9kfm728u6kd278g7alwz3n6esmf4szyjcuwgrhqmlt0qg9u33se
    lastmodified: "2026-09-18T08:03:20Z"
    mac: ENC[AES256_GCM,data:VCVYNoImIzfvgTH20fSb8y7iLwkvuWae7SHHaB17HRFnIf1/BTRG2RXicv1mm0ZJWjlkuCZQmBTczTO0ilLDG9cD/5jLDg/pumlRd3LuiBILco+9IMuD9l2S3iMS37cYvopcfwQSY4tSSMm0QjDQskHskFopXm05XetSuiEVn0Q=,iv:WMCDKink18YqLs8h0Fy2VLArKSUsKIJFL6c9zePtwF0=,tag:ok9dytHTZSesDp72qAsyPg==,type:str]
    mac_only_encrypted: true
    unencrypted_suffix: _unencrypted
    version: 3.13.1
