api:
    allowedSourceRanges:
        - ENC[AES256_GCM,data:fZkdy5s3KR36GJgfVaazcuHzZCVoFKkQlFmI,iv:mowvx+laCxIP6t3Un/sNiA38bnv8LTynqTq0TKxxPxo=,tag:NNDn2hrXH44tP2WKfKGtpQ==,type:comment]
        - ENC[AES256_GCM,data:AAADuWPOhV8U6BMUuO6u,iv:vy3Xl5OVYF4WSSVleJHfptdqIXq9LkdbyGhJzh2Z+Pw=,tag:u+aDaF7FQ9Xl9T1M2j8fcg==,type:str]
        - ENC[AES256_GCM,data:5ROyjTp/JVPxYvirdpQHxwKX5SXhqOFwXeVa,iv:4vd2EEWvJxNG1k475owT99YFFWhZXun72ChV18LkEMo=,tag:/wvFvHrrPvXIfCxSw88B6g==,type:comment]
        - ENC[AES256_GCM,data:2Sa7Lyg63vYDouuxy8Nyjg==,iv:WOGyhYZmSIRWbRTrs9JzLvY3CrmP1gmIqGtmGtKxLis=,tag:+i7iWurFPQICxmzunGO1zQ==,type:str]
        - ENC[AES256_GCM,data:DOX6aNSxCyENwVOpVxdinA8=,iv:P6vV7F1hwTXdQixLq1vjKLmPSt7rwdqmUFjr+0E1OJo=,tag:a8rAVHoTRa+cRBrh7sI/6Q==,type:comment]
        - ENC[AES256_GCM,data:UU5JWmM5nZ35PCV55g==,iv:sC7JnTAM+cYoeZfnWqroFkzR/Fc3QUhgMqnzWk9gdLs=,tag:R+l4bRiWWny5i4w3nvFGrQ==,type:str]
        - ENC[AES256_GCM,data:kf0yfLNg9bFEVNTXftl9uImllA==,iv:k3EBgWR8pkdK1XuZTkWMmCRNQMizWzNFBkdc0rvs1TQ=,tag:vnZAVivMRkOSMYOy6fs4cw==,type:comment]
        - ENC[AES256_GCM,data:ow+29NPE4fuu7DPBZVE=,iv:g/+nZsqz8RP3VpKxNeQw0qUO67YOee3Aqcm81dDQj+w=,tag:zMiKszGM0tN/SiXuwnS/5w==,type:str]
        - ENC[AES256_GCM,data:qINJiXD5yCYbwOBAro7cVDccXlc=,iv:DTjLreyBgKMfoScNiU2a2rxemgmQiuP/Q4cvBc7nRZU=,tag:+BDPKAETSLzM1p6KinbKRA==,type:comment]
        - ENC[AES256_GCM,data:KAzbj+7fGr0cvNIAgW5c,iv:4b+wtKoi9A12z84AOU4+y2WpJ3/FWbcBDQHZjF7oqDw=,tag:E4AWaaJMyB06DUIgSdZh1g==,type:str]
interops:
    organizationCode: ENC[AES256_GCM,data:Go+hGw==,iv:9CIajxjplgg4tvQyYxrD8hnmgeVB5NKYHCyURCJ+MWU=,tag:4ODZ4+hsbz271DTgJHXzIA==,type:int]
    organizationLabel: ENC[AES256_GCM,data:NsIaSOUkcLIu6PMEBg==,iv:lQhrC+O/fhZwZ0APF5sx6LH724Zh9OXrcDmnnIU3DzE=,tag:oHI0jNJwi1pDjBlE/mHN1w==,type:str]
    #ENC[AES256_GCM,data:9lv0n1Q96yJCOi/WkhAPPMIa6bYcr/uxOs6GU4BpjqFlehOKwtG/b5pJ,iv:MQuKa2DAhK+wusVeVV/yP0lC9MUASGMKJmSESSKPGTU=,tag:0Q9Vc4dYjyc6GCuAnrIGmg==,type:comment]
    subjectId: ENC[AES256_GCM,data:3yYPkFnp6YXHYppFvSKu9cyejde3IwgaTJpFqT7m/YQis5Mz/08Q,iv:8jBdKj6lPtkCO5xF7t0bIgfpDqqS2Jxr46CPzNwfwFA=,tag:+DlL1DxO7dtWrmBcvgR3rQ==,type:str]
    identityPath: ENC[AES256_GCM,data:QL0UGNQ=,iv:dL7ulEU0X8Fz3oPozVDJjeT6z9itBLFbdw+thcZ8tc4=,tag:aHH40nO+A0ROvkhRdCahFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgUXFRbXNnIEJBSzF2cTV6
            U1VyaDczUVVsNFpzdnZGWU9lRjVLSDJPd3lFWnlPRU1Rbko5cWZpZTZNK3VjOG1h
            Y1kybEZYU1hHWjl4N3RhMm5XL0FNbVZVeTRjRmc1YwpGSHZEbmxWM0JBWTJNQXdK
            VWRsZkZjSEVKOEhqMm5jM3l3OVhZSG9uZ2w4Ci0tLSBvdDVtZGhGelUyMFFCb29O
            bEx5ZHZlUWM5UGE5VTJpeE1jbDUrT01Wc0VzCsFYUJvtlu7U73lDSWZz4Pmc3MPV
            b5MEBDRlGNEK5623siG+kjr/UkRaqlk11FOaBrRtySAVoIG/wiTJNNsQycw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1q22yv67hk89v390rseukrx3mu5gzw9lpnngla4shn3efhzg2czn7cvdt8y3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRTRCU1J0eTZ2cHMxUzlK
            NkYxNjFlb2ZBS0dIYUpZRG0xSmlqOVlVM3pnCjMxR241Qi9pTVJYbCtYdnFFNUpY
            U1ZDZGRUOEczUGFvVVl3Ukdkb0JTYzgKLS0tIDJBbWJVd3BZQVJpTkRSRHhuN0Zk
            dEhRdjlhSG5oTjA1ak1MK1dSdGdSRmMKmB7ZEZn8n6ZH0Nrykmptidnsgt9WXYSc
            9b5IwE7L3ZBtCcX95FxbQpMeER7b5scnX4chHNy26A6trcBF62z1nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q2w07qws7tw5fhcsnxr33z6588exfnu2dpnsqhhqlvyxc0jf750qgrwv5t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgWWRzN2d3IEJGVE54Q09q
            RHZKMTJXSHA2eTROYWl6RHJCeDlySHB2VE5Lci9jRUlET3pndlp2RXAvRnZMV00z
            d0xGNWRNZTBGblZGcy9NYk5hdmhYZ29MeEY1RTArSQpqeW1XVTVkcGpKclZZM0dp
            eG5BRFpYY0djK0Izck9Pd3NubU1GZ2NvVDRzCi0tLSBMUFY4MWJXRFJYMEpBOWFK
            eEJvN0VTSkpydmVOOTBENHhXMVR0STZSVUgwChj/k2I5G3EAwagMRDVMif2nEFdT
            +kDgYeTyhMlS9ueDkI/HUsxDwakTcTp6ZJACc3XmSXRnWtE3m6a9++Gr4CU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tpm1qdeuratg9kfm728u6kd278g7alwz3n6esmf4szyjcuwgrhqmlt0qg9u33se
    lastmodified: "2026-09-18T08:04:37Z"
    mac: ENC[AES256_GCM,data:FVuuZI+rq7hU9RPvj7vs1+CPVe8sGrA1ZktTccACnSwb8zEdlL7KR4m6Q3gudNzoD/TnKVZQEsgHrql2zSAkQPZkp0et3YvhZdeHQzUG7LBzcpNi5nbtppEij3wBk6gJYiQylP6GA5N2RzMB5FJgs0wJLkQ7W/+AnM94sTWDKCQ=,iv:3bsGU0rs6WUGqUxmZ+zF/655NHlsnKPHVepPndmN0G0=,tag:JpzrHXqZiR2f32GBUpI4yw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
