apiVersion: v1
kind: Service
metadata:
  name: {{ include "interops-a.fullname" . }}
  labels:
    {{- include "interops-a.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "interops-a.selectorLabels" . | nindent 4 }}
