apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-relay-database
  labels:
    {{- include "api-relay.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: api-relay-database
    creationPolicy: Owner
  data:
    {{- range $property := list "host" "port" "name" }}
    - secretKey: {{ $property }}
      remoteRef:
        key: name:api-relay-database-connection-{{ $.Values.environment }}
        version: latest_enabled
        property: {{ $property }}
    {{- end }}
    {{- range $property := list "app_user" "app_password" "jobs_user" "jobs_password" }}
    - secretKey: {{ $property }}
      remoteRef:
        key: name:api-relay-database-{{ $.Values.environment }}
        version: latest_enabled
        property: {{ $property }}
    {{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-relay-django
  labels:
    {{- include "api-relay.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: api-relay-django
    creationPolicy: Owner
  data:
    {{- range $property := list "secret_key" "secret_key_fallbacks" }}
    - secretKey: {{ $property }}
      remoteRef:
        key: name:api-relay-django-{{ $.Values.environment }}
        version: latest_enabled
        property: {{ $property }}
    {{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-relay-api-token
  labels:
    {{- include "api-relay.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: api-relay-api-token
    creationPolicy: Owner
  data:
    # Only the hash is propagated here (the plaintext token stays in Secret Manager)
    - secretKey: hashed_token
      remoteRef:
        key: name:api-relay-api-token-{{ .Values.environment }}
        version: latest_enabled
        property: hashed_token
