apiVersion: v2
name: argocd
description: ArgoCD GitOps controller for emplois-cnav
type: application
version: 0.1.0
appVersion: "2.14"
keywords:
  - argocd
  - gitops
maintainers:
  - name: GIP Inclusion
dependencies:
  - name: argo-cd
    alias: argocd
    version: "9.3.6"
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    alias: argocdapps
    version: 2.0.4
    repository: https://argoproj.github.io/argo-helm
